### ISSUE TITLE
Tip 315: why `... + std::size_t{}`?

### ISSUE THREAD

**Issue by daixtrose** [QuantlabFinancial/cpp_tip_of_the_week#112]
In [315.md](https://github.com/QuantlabFinancial/cpp_tip_of_the_week/blob/master/tips/315.md) the first proposed solution is 

```c++
template<class T, class... Ts>
constexpr auto count_compatible = (std::is_layout_compatible_v<T, Ts> + ... + std::size_t{});
```
but the tests pass without `+ std::size_t{}`. 
```c++
template<class T, class... Ts>
constexpr auto count_compatible = (std::is_layout_compatible_v<T, Ts> + ...);
```
I think this is due to C++ being weird (aka have automatic conversions)
```c++
constexpr bool b1 = true;
constexpr bool b2 = true;
constexpr auto test = b1 + b2;
static_assert(2 == test);
static_assert(std::is_same_v<decltype(test), const int>);
```

The introduction of `size_t` might help for **very** large type lists, but it probably should go first. Not sure though. 

```c++
template<class T, class... Ts>
constexpr auto count_compatible = (std::size_t{} + ... + std::is_layout_compatible_v<T, Ts>);
```

Am I missing something?

**Comment by daixtrose** [comment]
Peter Bindels provided [an excellent reason](https://mastodon.social/@dascandy42/109816810748335820): Adding `std::size_t{}` makes it work for single argument, but only for the trailing form `std::is_layout_compatible_v<T, Ts> + ... + std::size_t{}`:

```
static_assert(0 == count_compatible<int>);
```

**Comment by krzysztof-jusiak** [comment]
:+1:
