### ISSUE TITLE
std::ostream_joiner in C++20

### ISSUE THREAD

**Issue by Ukilele** [QuantlabFinancial/cpp_tip_of_the_week#6]
Hey,
these tips of the week look really interesting and informative, thanks for sharing them.
But I am not sure if it is correct what you write in [Tip190](https://github.com/QuantlabFinancial/cpp_tip_of_the_week/blob/master/190.md). I think std::ostream_joiner did not get added to C++20, or did it?

Regards,
Kilian

**Comment by krzysztof-jusiak** [comment]
Hey Kilian,

Thanks! And you are right, std::ostream_joiner is not part of any std yet :( Sorry for the confusion.
